interface CloudflareEnv {
	BROWSER: import("@cloudflare/puppeteer").BrowserWorker;
	CLOUDFLARE_ACCESS_AUD: string;
	CLOUDFLARE_ACCESS_SERVICE_CLIENT_ID: string;
	CLOUDFLARE_ACCESS_SERVICE_CLIENT_SECRET: string;
	CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
	INSTACONTENT_PUBLIC_BASE_URL: string;
	INSTAGRAM_ACCESS_TOKEN: string;
	INSTAGRAM_ACCOUNT_ID: string;
	INSTAGRAM_AUTOMATION_SIGNING_KEY: string;
	INSTAGRAM_GRAPH_API_VERSION: string;
	INSTAGRAM_MEDIA: R2Bucket;
	INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
	INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
	INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
}

declare namespace Cloudflare {
	interface Env {
		BROWSER: import("@cloudflare/puppeteer").BrowserWorker;
		CLOUDFLARE_ACCESS_AUD: string;
		CLOUDFLARE_ACCESS_SERVICE_CLIENT_ID: string;
		CLOUDFLARE_ACCESS_SERVICE_CLIENT_SECRET: string;
		CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
		INSTACONTENT_PUBLIC_BASE_URL: string;
		INSTAGRAM_ACCESS_TOKEN: string;
		INSTAGRAM_ACCOUNT_ID: string;
		INSTAGRAM_AUTOMATION_SIGNING_KEY: string;
		INSTAGRAM_GRAPH_API_VERSION: string;
		INSTAGRAM_MEDIA: R2Bucket;
		INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
		INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
		INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
	}
}

declare namespace NodeJS {
	interface ProcessEnv {
		CLOUDFLARE_ACCESS_AUD: string;
		CLOUDFLARE_ACCESS_SERVICE_CLIENT_ID: string;
		CLOUDFLARE_ACCESS_SERVICE_CLIENT_SECRET: string;
		CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
		INSTACONTENT_PUBLIC_BASE_URL: string;
		INSTAGRAM_ACCESS_TOKEN: string;
		INSTAGRAM_ACCOUNT_ID: string;
		INSTAGRAM_AUTOMATION_SIGNING_KEY: string;
		INSTAGRAM_GRAPH_API_VERSION: string;
		INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
		INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
		INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
	}
}
