interface CloudflareEnv {
	CLOUDFLARE_ACCESS_AUD: string;
	CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
	INSTAGRAM_ACCESS_TOKEN: string;
	INSTAGRAM_ACCOUNT_ID: string;
	INSTAGRAM_GRAPH_API_VERSION: string;
	INSTAGRAM_MEDIA: R2Bucket;
	INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
	INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
}

declare namespace Cloudflare {
	interface Env {
		CLOUDFLARE_ACCESS_AUD: string;
		CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
		INSTAGRAM_ACCESS_TOKEN: string;
		INSTAGRAM_ACCOUNT_ID: string;
		INSTAGRAM_GRAPH_API_VERSION: string;
		INSTAGRAM_MEDIA: R2Bucket;
		INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
		INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
	}
}

declare namespace NodeJS {
	interface ProcessEnv {
		CLOUDFLARE_ACCESS_AUD: string;
		CLOUDFLARE_ACCESS_TEAM_DOMAIN: string;
		INSTAGRAM_ACCESS_TOKEN: string;
		INSTAGRAM_ACCOUNT_ID: string;
		INSTAGRAM_GRAPH_API_VERSION: string;
		INSTAGRAM_MEDIA_PUBLIC_BASE_URL: string;
		INSTAGRAM_PUBLISH_ADMIN_EMAILS: string;
	}
}
